apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: admin123
          - name: MYSQL_DATABASE
            value: mediawiki
          - name: MYSQL_USER
            value: mediawiki
          - name: MYSQL_PASSWORD
            value: mediawiki-password
        ports:
        - containerPort: 3306
          name: mysql
        resources:
          requests:
            memory: "256Mi"   # Request 256 MiB of memory
            cpu: "100m"        # Request 0.1 CPU cores (100 milliCPU)
          limits:
            memory: "512Mi"    # Limit memory usage to 512 MiB
            cpu: "500m"        # Limit CPU usage to 0.5 CPU cores (500 milliCPU)
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
 